#11 Поднять сервер
htmlacademy-nodejs/663115-keksobooking pull request #10
Opened 2018-10-23 22:57 UTC by sitesmake

2018-10-25 13:07 UTC, kicumkicum requested changes

2018-10-25 13:07 UTC, kicumkicum commented on src/commands/server.js
> +const defaultPort = 3000;
Подобного рода констасты лучше писать капсом, разделяя слова нижним подчеркиванием.
Это настоящие константы и нужно сообщить об этом разработчикам.
Под настоящими константами подразумевается то, что важно для модуля. То, что конфигурирует его.
То, что записано в шапке модуля, сразу после зависимостей.

2018-10-25 13:07 UTC, kicumkicum commented on src/commands/server.js
> +    const encoding = fileType.substr(0, 5) === `image` ? `base64` : `utf-8`;
вместо `substr` лучше использовать `includes` или `indexOf`. `5` оттягивает внимание и порождает вопросы.
Предложенные методы будут работать условно быстрее, потому что количество операций сократится с 2 до 1.
И читать код будет легче, потому что исчезнет магическая константа `5`.
Только нужно не забыть добавить `/` -> `images/`, что бы было однозначно, как с протоколами `http:`

2018-10-25 13:07 UTC, kicumkicum commented on src/commands/server.js
> +    const encoding = fileType.substr(0, 5) === `image` ? `base64` : `utf-8`;
действительно нужно отдавать картинки в `base64`? Почему не как картинки, бинарными данными?

2018-10-25 13:07 UTC, kicumkicum commented on src/commands/server.js
> +    }
FIY: можно `const port = process.argv[3] || defaultPort;`

2018-10-25 13:11 UTC, kicumkicum reviewed
В целом, все очень даже хорошо. Задание решена. 👍 
Осталось немного довести до production вида 
Который не стыдно и сеньорам всяким показывать)

2018-10-25 13:11 UTC, kicumkicum commented on src/commands/server.js
> +  try {
для чего здесь `try`? Что он должен перехватить?

2018-10-25 13:46 UTC, sitesmake commented on src/commands/server.js
> +const defaultPort = 3000;
done

2018-10-25 14:32 UTC, sitesmake commented on src/commands/server.js
> +    const encoding = fileType.substr(0, 5) === `image` ? `base64` : `utf-8`;
done

2018-10-25 14:33 UTC, sitesmake commented on src/commands/server.js
> +    const encoding = fileType.substr(0, 5) === `image` ? `base64` : `utf-8`;
done

2018-10-25 14:35 UTC, sitesmake commented on src/commands/server.js
> +    }
done

2018-10-26 11:40 UTC, kicumkicum commented on src/commands/server.js
> +    let port = process.argv[3] || DEFAULT_PORT;
`port` больше не переписывается, поэтому нужно `const`

2018-10-26 11:40 UTC, kicumkicum commented on src/commands/server.js
> +    res.end(`500. Format ${path.extname(requestFilePath)} is not supported`);
тут ты закрываешь соединение, но затем устанавливаешь заголовок и начинаешь читать файл.
Это явно оверхед и нужно что то сделать

2018-10-26 11:40 UTC, kicumkicum commented on src/commands/server.js
> +  readFile(requestFilePath, encoding)
с промисами такая штука, что если его вернуть в функции, то можно построить цепочку. А если нет, то нельзя. 
И достаточно часто бывает так, что неиспользуемые в цепочках функции с промисами нужно добавлять в цепочки.
И нужно идти в них и писать `return`.
А когда ты иногда возвращаешь промисы, а иногда не возвращаешь, начинаешь забывать писать `return` там, где он нужен и получаешь баги, которые не всегда просто отловить. Из за одного `return`.
Поэтому я для себя взял за правило, всегда возвращать промис - писать `return` - даже если сейчас этот результат никому не нужен. Даже если это слушатель, результат которого точно никому не нужен.

2018-10-26 11:54 UTC, sitesmake commented on src/commands/server.js
> +    let port = process.argv[3] || DEFAULT_PORT;
done

2018-10-26 12:06 UTC, sitesmake commented on src/commands/server.js
> +  readFile(requestFilePath, encoding)
done

2018-10-26 12:06 UTC, sitesmake commented on src/commands/server.js
> +    res.end(`500. Format ${path.extname(requestFilePath)} is not supported`);
done

2018-10-26 12:24 UTC, kicumkicum approved these changes

2018-10-26 12:24 UTC, merged