#12 Прибытие поезда на вокзал Ла Сьота
htmlacademy-nodejs/663115-keksobooking pull request #11
Opened 2018-10-27 07:08 UTC by sitesmake

…ction)

2018-10-27 18:57 UTC, kicumkicum commented
Ну тут еще нужно express подключить и что там еще по заданию

2018-10-29 12:17 UTC, kicumkicum commented
Уже можно смотреть? Тревис то падает.

2018-10-30 09:55 UTC, kicumkicum requested changes

2018-10-30 09:55 UTC, kicumkicum commented on package.json
> +    "test": "npm run test:lint && find ./test -name '*.test.js' | xargs npm run test:mocha"
а что так сложно?

и скорее всего не будет работать на винде

2018-10-30 09:55 UTC, kicumkicum commented on package.json
> +    "supertest": "^3.3.0"
крыжика `^` не должно быть
Ты установил без фиксации версии.

Что бы исправить, удалить крыжик недостаточно.
Нужно удалить через npm а потом поставить сразу

2018-10-30 09:55 UTC, kicumkicum commented on src/commands/generate.js
> +  execute(count, path, customDate = null) {
почему `null`?

2018-10-30 09:55 UTC, kicumkicum commented on src/commands/server.js
> +    this.code = 404;
Точно 404? Ведь ниже ты сообщаешь об ошибке передаваемых параметров

2018-10-30 09:55 UTC, kicumkicum commented on src/commands/server.js
> +});
это ты добавил для отладки. Больше же не нужно? Можно выпилить?

2018-10-30 09:55 UTC, kicumkicum commented on src/generate-entity.js
> +    date: ~~customDate || Math.floor((new Date() - Math.random(Param.TIME_MIN_OFFSET)) / 1000)
что за магия `~~`?

2018-10-30 09:55 UTC, kicumkicum commented on test/get-offers.test.js
> +const assert = require(`assert`);
по алфавиту бы

2018-10-30 09:55 UTC, kicumkicum commented on test/get-offers.test.js
> +  });
Думаю, что нужен тест для запроса без даты

2018-10-30 09:55 UTC, kicumkicum commented on test/get-offers.test.js
> +      });
а для чего `catch`?

2018-10-30 12:35 UTC, sitesmake commented on package.json
> +    "test": "npm run test:lint && find ./test -name '*.test.js' | xargs npm run test:mocha"
Отсюда смотрел https://gist.github.com/timoxley/1721593#gistcomment-953153

2018-10-30 12:44 UTC, sitesmake commented on package.json
> +    "supertest": "^3.3.0"
done

2018-10-30 12:55 UTC, sitesmake commented on src/commands/server.js
> +    this.code = 404;
done

2018-10-30 12:55 UTC, sitesmake commented on src/commands/generate.js
> +  execute(count, path, customDate = null) {
done

2018-10-30 12:55 UTC, sitesmake commented on src/commands/server.js
> +});
done

2018-10-30 12:55 UTC, sitesmake commented on src/generate-entity.js
> +    date: ~~customDate || Math.floor((new Date() - Math.random(Param.TIME_MIN_OFFSET)) / 1000)
done

2018-10-30 12:55 UTC, sitesmake commented on test/get-offers.test.js
> +const assert = require(`assert`);
done

2018-10-30 13:22 UTC, sitesmake commented on test/get-offers.test.js
> +  });
done?

2018-10-30 13:22 UTC, sitesmake commented on test/get-offers.test.js
> +      });
Если возникнет ошибка в процессе - здесь отловится - и будет видна причина. Нет?

2018-10-30 13:23 UTC, sitesmake commented on package.json
> +    "test": "npm run test:lint && find ./test -name '*.test.js' | xargs npm run test:mocha"
А как можно упростить?

2018-10-30 20:23 UTC, kicumkicum commented on package.json
> +    "test": "npm run test:lint && find ./test -name '*.test.js' | xargs npm run test:mocha"
я ж писал, что последний коммент) В самом низу

2018-10-30 20:25 UTC, kicumkicum commented
код выпилил, а тесты нет. Сборка и упала

2018-10-30 20:26 UTC, kicumkicum commented on test/get-offers.test.js
> +      });
Если возникнет ошибка, то тест должен сразу упасть. И должно быть видно то же самое

2018-10-30 20:27 UTC, kicumkicum commented on test/get-offers.test.js
> +      });
Попробуй закоментить `catch` и бросить там где нибудь ексепшен.
Посмотри, действительно ли так будет. Если да, то можно будет выпилить `catch`

2018-10-30 20:28 UTC, kicumkicum commented on test/get-offers.test.js
> +  });
done

2018-10-30 20:30 UTC, kicumkicum commented on src/generate-entity.js
> +    date: ~~customDate || Math.floor((new Date() - Math.random(Param.TIME_MIN_OFFSET)) / 1000)
a `customDate` какого типа может быть? `Date` или `undefined`?
Если да, то `parseInt` слишком жирно для этого. Он только для строк

2018-10-30 20:33 UTC, kicumkicum commented on src/commands/generate.js
> +  execute(count, path, customDate = null) {
`= undefined` это оператор подергивания же)
Эта операция присваивания выполнится в случае, если `customDate` не определен.
То есть его не передали и он `undefined`.

2018-10-31 05:07 UTC, sitesmake commented on test/get-offers.test.js
> +      });
done

2018-10-31 05:17 UTC, sitesmake commented on src/commands/generate.js
> +  execute(count, path, customDate = null) {
done

2018-10-31 05:20 UTC, sitesmake commented on src/generate-entity.js
> +    date: ~~customDate || Math.floor((new Date() - Math.random(Param.TIME_MIN_OFFSET)) / 1000)
По тз date - число, дата размещения, представляет собой timestamp в формате UNIX. Представляет собой случайное число в интервале от сейчас минус 7 дней.
Когда date приходит из params - он String, привел его к Integer.

2018-10-31 05:23 UTC, sitesmake commented on package.json
> +    "test": "npm run test:lint && find ./test -name '*.test.js' | xargs npm run test:mocha"
done?

2018-10-31 08:46 UTC, kicumkicum commented on test/get-offers.test.js
> +      });
ты попробовал? Все так и есть?

2018-10-31 08:50 UTC, kicumkicum commented on src/generate-entity.js
> +    date: ~~customDate || Math.floor((new Date() - Math.random(Param.TIME_MIN_OFFSET)) / 1000)
ок

2018-10-31 08:50 UTC, kicumkicum commented on package.json
> +    "test": "npm run test:lint && find ./test -name '*.test.js' | xargs npm run test:mocha"
done

2018-10-31 13:53 UTC, sitesmake commented on test/get-offers.test.js
> +      });
Без catch assert.true пишет ошибку - так что здесь действительно не нужен.

2018-10-31 14:36 UTC, merged