Started tests
htmlacademy-nodejs/663115-keksobooking pull request #7
Opened 2018-10-04 19:02 UTC by sitesmake

2018-10-08 13:46 UTC, kicumkicum requested changes
Стало определенно лучше 👍  Но есть еще пара моментов

2018-10-08 13:46 UTC, kicumkicum commented on src/generate-entity.js
> +  return Math.floor(new Date() / 1000 - Math.random(RANGE_FOR_DATES));
Так как для JS нативное время ms, то и все константы и операции нужно делать в ms.
И переводить в секунды, минуты, часы, etc. уже там, где требует клиент.

2018-10-08 13:46 UTC, kicumkicum commented on src/generate-entity.js
> +const mockAddress = (x, y) => {
а почему `mock`?

2018-10-08 13:46 UTC, kicumkicum commented on test/generate-entity.test.js
> +    const TIME_MIN = Math.floor(new Date() / 1000 - Math.random(7 * 24 * 60 * 60));
можно ли полагать, что разработчик, который изменит значение в модуле, не забудет поменять это же значение здесь?

2018-10-08 13:46 UTC, kicumkicum commented on package.json
> +    "random-item": "1.0.0"
либы больше же не используйутся? Можно удалять?

2018-10-08 14:34 UTC, sitesmake commented on package.json
> +    "random-item": "1.0.0"
done

2018-10-08 14:34 UTC, sitesmake commented on src/generate-entity.js
> +const mockAddress = (x, y) => {
done

2018-10-08 14:49 UTC, sitesmake commented on src/generate-entity.js
> +  return Math.floor(new Date() / 1000 - Math.random(RANGE_FOR_DATES));
done?

2018-10-08 14:49 UTC, sitesmake commented on test/generate-entity.test.js
> +    const TIME_MIN = Math.floor(new Date() / 1000 - Math.random(7 * 24 * 60 * 60));
done?

2018-10-09 08:39 UTC, kicumkicum commented on src/utils/random.js
> +const sortArray = (ary) => {
`ary` имелось ввиду `arr`? Но вообще имена лучше не сокращать.
Понятно, что есть общепринятые сокращения, типа `err, min, max`.
Сокращения могут быть устоявшимися на уровне команды.
Но в остальном не стоит этого делать. И не экономить на буквах.

2018-10-09 08:39 UTC, kicumkicum commented on src/generate-entity.js
> +const featuresList = () => {
имени не хватает глагола

2018-10-09 08:39 UTC, kicumkicum commented on src/generate-entity.js
> +  let features = [];
тут точно нужен `let`?

2018-10-09 08:39 UTC, kicumkicum commented on test/generate-entity.test.js
> +    expect([`flat`, `palace`, `house`, `bungalo`]).to.include(entity.offer.type);
дублирование

2018-10-09 08:39 UTC, kicumkicum commented on test/generate-entity.test.js
> +    const TIME_MIN = Math.floor(new Date() - Param.TIME_MIN_OFFSET);
но ведь это не константы. Почему они капсом?

2018-10-09 08:39 UTC, kicumkicum commented on test/generate-entity.test.js
> +    const TIME_NOW = Math.floor(new Date());
а что тут округлять?)

2018-10-09 08:39 UTC, kicumkicum commented on src/generate-entity.js
> +
то два переноса, то один. Это подчинено каким нибудь правилам?)

2018-10-09 08:39 UTC, kicumkicum commented on src/generate-entity.js
> +const mockAvatar = () => {
этот метод что то мокает?

2018-10-09 14:40 UTC, sitesmake commented on src/utils/random.js
> +const sortArray = (ary) => {
done

2018-10-09 15:34 UTC, sitesmake commented on src/generate-entity.js
> +const featuresList = () => {
done

2018-10-09 15:51 UTC, sitesmake commented on src/generate-entity.js
> +  let features = [];
done?

2018-10-09 15:53 UTC, sitesmake commented on test/generate-entity.test.js
> +    expect([`flat`, `palace`, `house`, `bungalo`]).to.include(entity.offer.type);
done

2018-10-09 15:55 UTC, sitesmake commented on test/generate-entity.test.js
> +    const TIME_MIN = Math.floor(new Date() - Param.TIME_MIN_OFFSET);
done

2018-10-09 16:01 UTC, sitesmake commented on test/generate-entity.test.js
> +    const TIME_NOW = Math.floor(new Date());
спросил в Слэке

2018-10-09 16:02 UTC, sitesmake commented on src/generate-entity.js
> +
Отделял импорт от констант от тела от экспорта - но везде пока оставлю один перенос.
done

2018-10-09 16:03 UTC, sitesmake commented on src/generate-entity.js
> +const mockAvatar = () => {
done?

2018-10-09 17:31 UTC, sitesmake commented on test/generate-entity.test.js
> +    const TIME_NOW = Math.floor(new Date());
done

2018-10-10 08:46 UTC, kicumkicum commented
> Current Github conversation fixes

Не очень хорошее имя для коммита по двум причинам.
1. Начинается не с глагола
2. По сообщенийу не понятно, что же делает коммит. Пока не заглянешь внутрь, не поймешь.
Привязка к внешнему контексту затрудняет понимание истории. Через неделйу мы уже забудем, о чем разговаривали, где и почему код написан именно таким образом.

2018-10-10 08:53 UTC, kicumkicum approved these changes

2018-10-10 08:53 UTC, merged